name: "Dragon Knight"
description: "Dragon Knight on Boulderfist"
url: http://dk.chapley.com

gems: [jekyll-paginate, jekyll-gist]

paginate: 3

permalink: pretty

highlighter: pygments

resource_list:
  How Bad Am I?: '/log_guide/'
  Learn Your Class: '/learn_your_class/'
  

