name: "Dragon Knight"
description: "Dragon Knight on Boulderfist"
url: http://dk.chapley.com

paginate: 3

permalink: pretty
relative_permalinks: true

markdown: rdiscount
highlighter: pygments

pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Raid Team: '/raid_team/'

resource_list:
  Best in Slot: '/best_in_slot/'
  Weak Auras: '/weak_aura/'
  How Bad Am I?: '/log_guide/'
  Learn Your Class: '/learn_your_class/'
